import type { Banner, Category, Reward, Product } from "./types";

export const categories: Category[] = [
  {
    slug: "emagrecimento",
    name: "Emagrecimento",
    tagline: "Fórmulas para redução de medidas",
    icon: "Flame",
    gradient: ["#245A42", "#12261C"],
    accent: "#E0552B",
  },
  {
    slug: "beleza",
    name: "Beleza & Skincare",
    tagline: "Colágeno, pele, cabelo e unhas",
    icon: "Sparkles",
    gradient: ["#2E6B4F", "#163B2C"],
    accent: "#C24B86",
  },
  {
    slug: "saude",
    name: "Saúde & Bem-estar",
    tagline: "Vitaminas e suporte diário",
    icon: "HeartPulse",
    gradient: ["#1B4332", "#0C1E16"],
    accent: "#1E7BA8",
  },
  {
    slug: "longevidade",
    name: "Longevidade",
    tagline: "Antienvelhecimento e vitalidade",
    icon: "Leaf",
    gradient: ["#3E8B68", "#1B4332"],
    accent: "#2F8F5B",
  },
  {
    slug: "fitness",
    name: "Fitness & Performance",
    tagline: "Energia e recuperação muscular",
    icon: "Dumbbell",
    gradient: ["#245A42", "#0C1E16"],
    accent: "#CF3B2E",
  },
  {
    slug: "imunidade",
    name: "Imunidade",
    tagline: "Defesas naturais do corpo",
    icon: "Shield",
    gradient: ["#2E6B4F", "#12261C"],
    accent: "#E38A16",
  },
  {
    slug: "sono",
    name: "Sono & Relaxamento",
    tagline: "Noites tranquilas, menos estresse",
    icon: "Moon",
    gradient: ["#163B2C", "#0C1E16"],
    accent: "#4A54A8",
  },
  {
    slug: "dermato",
    name: "Dermocosméticos",
    tagline: "Cuidados manipulados para a pele",
    icon: "Droplets",
    gradient: ["#3E8B68", "#163B2C"],
    accent: "#12968A",
  },
];

export const products: Product[] = [
  {
    id: "p01",
    slug: "termogenico-slim-detox",
    name: "Termogênico Slim Detox",
    category: "emagrecimento",
    price: 89.9,
    oldPrice: 129.9,
    rating: 4.8,
    reviews: 214,
    shortDescription: "Cafeína, chá verde e picolinato de cromo para acelerar o metabolismo.",
    description:
      "Fórmula manipulada que combina cafeína anidra, extrato de chá verde e picolinato de cromo para auxiliar na aceleração do metabolismo, no controle do apetite e na queima de gordura. Produzido sob rigoroso controle de qualidade em nossa farmácia de manipulação.",
    benefits: ["Acelera o metabolismo", "Ajuda no controle do apetite", "Mais disposição no dia a dia"],
    badges: ["Manipulado", "Vegano"],
    bestseller: true,
    special: true,
  },
  {
    id: "p02",
    slug: "redutor-de-medidas-premium",
    name: "Redutor de Medidas Premium",
    category: "emagrecimento",
    price: 119.9,
    oldPrice: 159.9,
    rating: 4.7,
    reviews: 156,
    shortDescription: "Blend com Morosil® e cromo para redução de gordura abdominal.",
    description:
      "Combinação de Morosil® (extrato de laranja moro), cromo e fibras que auxilia na redução da circunferência abdominal e no equilíbrio da glicemia. Ideal como suporte a uma rotina de alimentação equilibrada e exercícios.",
    benefits: ["Reduz medidas", "Equilibra a glicemia", "Sensação de saciedade"],
    badges: ["Manipulado", "Com Morosil®"],
    special: true,
  },
  {
    id: "p03",
    slug: "colageno-verisol-acido-hialuronico",
    name: "Colágeno Verisol® + Ácido Hialurônico",
    category: "beleza",
    price: 139.9,
    oldPrice: 179.9,
    rating: 4.9,
    reviews: 389,
    shortDescription: "Firmeza e elasticidade da pele com peptídeos bioativos.",
    description:
      "Peptídeos de colágeno Verisol® associados ao ácido hialurônico e vitamina C para estimular a firmeza, a elasticidade e a hidratação da pele, além de fortalecer unhas e cabelos. Sabor neutro, fácil de dissolver.",
    benefits: ["Firmeza e elasticidade", "Reduz linhas finas", "Fortalece unhas e cabelos"],
    badges: ["Manipulado", "Verisol®"],
    bestseller: true,
    special: true,
  },
  {
    id: "p04",
    slug: "capsulas-de-beleza-biotina-zinco",
    name: "Cápsulas de Beleza — Biotina + Zinco",
    category: "beleza",
    price: 69.9,
    rating: 4.6,
    reviews: 132,
    shortDescription: "Nutrição para cabelos fortes, unhas resistentes e pele saudável.",
    description:
      "Fórmula com biotina, zinco quelato, selênio e silício orgânico que nutre os folículos capilares, fortalece as unhas e contribui para a saúde da pele. Uso diário recomendado por ciclos de 90 dias.",
    benefits: ["Cabelos mais fortes", "Unhas resistentes", "Pele nutrida"],
    badges: ["Manipulado", "Sem glúten"],
  },
  {
    id: "p05",
    slug: "vitamina-d3-k2",
    name: "Vitamina D3 + K2 (MK-7)",
    category: "saude",
    price: 59.9,
    oldPrice: 79.9,
    rating: 4.9,
    reviews: 421,
    shortDescription: "Dupla essencial para ossos, imunidade e saúde cardiovascular.",
    description:
      "Associação de vitamina D3 e vitamina K2 (MK-7) que favorece a absorção de cálcio, a saúde óssea, o bom funcionamento do sistema imunológico e a saúde cardiovascular. Cápsulas oleosas de fácil absorção.",
    benefits: ["Saúde óssea", "Suporte imunológico", "Melhor absorção de cálcio"],
    badges: ["Manipulado", "Alta absorção"],
    bestseller: true,
    special: true,
  },
  {
    id: "p06",
    slug: "magnesio-dimalato",
    name: "Magnésio Dimalato",
    category: "saude",
    price: 54.9,
    rating: 4.8,
    reviews: 276,
    shortDescription: "Energia, função muscular e redução da fadiga.",
    description:
      "O magnésio dimalato é altamente biodisponível e participa de mais de 300 reações no organismo, auxiliando na produção de energia, na função muscular e nervosa e na redução do cansaço e da fadiga.",
    benefits: ["Mais energia", "Reduz cãibras", "Melhora a recuperação"],
    badges: ["Manipulado", "Vegano"],
  },
  {
    id: "p07",
    slug: "omega-3-tg",
    name: "Ômega 3 TG (EPA + DHA)",
    category: "saude",
    price: 94.9,
    oldPrice: 124.9,
    rating: 4.7,
    reviews: 198,
    shortDescription: "Alta concentração de EPA e DHA na forma de triglicerídeos.",
    description:
      "Óleo de peixe purificado na forma de triglicerídeos (TG), com alta concentração de EPA e DHA para apoiar a saúde do coração, do cérebro e das articulações. Livre de metais pesados, com certificado de pureza.",
    benefits: ["Saúde do coração", "Foco e memória", "Ação anti-inflamatória"],
    badges: ["Manipulado", "Ultra purificado"],
    special: true,
  },
  {
    id: "p08",
    slug: "resveratrol-coenzima-q10",
    name: "Resveratrol + Coenzima Q10",
    category: "longevidade",
    price: 149.9,
    rating: 4.8,
    reviews: 143,
    shortDescription: "Antioxidantes que combatem o envelhecimento celular.",
    description:
      "Combinação de resveratrol e coenzima Q10, poderosos antioxidantes que combatem os radicais livres, apoiam a produção de energia celular e contribuem para a vitalidade e a longevidade saudável.",
    benefits: ["Ação antioxidante", "Energia celular", "Vitalidade"],
    badges: ["Manipulado", "Antioxidante"],
  },
  {
    id: "p09",
    slug: "nad-booster-nicotinamida",
    name: "NAD+ Booster (Nicotinamida Ribosídeo)",
    category: "longevidade",
    price: 189.9,
    oldPrice: 229.9,
    rating: 4.9,
    reviews: 87,
    shortDescription: "Suporte à energia celular e ao envelhecimento saudável.",
    description:
      "A nicotinamida ribosídeo é precursora do NAD+, molécula essencial para a produção de energia e o reparo celular. Auxilia na disposição, no metabolismo e no envelhecimento saudável.",
    benefits: ["Eleva os níveis de NAD+", "Mais disposição", "Reparo celular"],
    badges: ["Manipulado", "Premium"],
    special: true,
  },
  {
    id: "p10",
    slug: "creatina-monohidratada",
    name: "Creatina Monohidratada Creapure®",
    category: "fitness",
    price: 99.9,
    oldPrice: 139.9,
    rating: 4.9,
    reviews: 512,
    shortDescription: "Força, potência e ganho de massa muscular.",
    description:
      "Creatina monohidratada Creapure® de altíssima pureza, referência mundial em qualidade. Auxilia no aumento de força, potência e desempenho nos treinos, além de contribuir para o ganho de massa muscular.",
    benefits: ["Mais força nos treinos", "Ganho de massa magra", "Recuperação acelerada"],
    badges: ["Manipulado", "Creapure®"],
    bestseller: true,
    special: true,
  },
  {
    id: "p11",
    slug: "pre-treino-focus",
    name: "Pré-treino Focus",
    category: "fitness",
    price: 84.9,
    rating: 4.6,
    reviews: 176,
    shortDescription: "Energia, foco e resistência para treinos intensos.",
    description:
      "Blend de cafeína, beta-alanina, taurina e tirosina que proporciona energia, foco mental e resistência, retardando a fadiga durante os treinos mais intensos.",
    benefits: ["Energia imediata", "Foco e concentração", "Menos fadiga"],
    badges: ["Manipulado", "Alta performance"],
  },
  {
    id: "p12",
    slug: "vitamina-c-lipossomal",
    name: "Vitamina C Lipossomal",
    category: "imunidade",
    price: 74.9,
    oldPrice: 99.9,
    rating: 4.8,
    reviews: 231,
    shortDescription: "Absorção superior para fortalecer a imunidade.",
    description:
      "Vitamina C em tecnologia lipossomal, que garante absorção muito superior à vitamina C tradicional. Poderoso antioxidante que fortalece o sistema imunológico e apoia a produção de colágeno.",
    benefits: ["Reforça a imunidade", "Absorção superior", "Ação antioxidante"],
    badges: ["Manipulado", "Lipossomal"],
    special: true,
  },
  {
    id: "p13",
    slug: "zinco-quelato-propolis",
    name: "Zinco Quelato + Própolis",
    category: "imunidade",
    price: 49.9,
    rating: 4.7,
    reviews: 118,
    shortDescription: "Dupla protetora para as defesas do organismo.",
    description:
      "Zinco quelato de alta biodisponibilidade associado ao extrato de própolis verde, com ação imunomoduladora e antioxidante para reforçar as defesas naturais do corpo ao longo do ano.",
    benefits: ["Fortalece as defesas", "Ação antioxidante", "Saúde da pele"],
    badges: ["Manipulado", "Própolis verde"],
  },
  {
    id: "p14",
    slug: "melatonina-3mg",
    name: "Melatonina 3mg",
    category: "sono",
    price: 39.9,
    oldPrice: 54.9,
    rating: 4.8,
    reviews: 344,
    shortDescription: "Regula o sono e melhora a qualidade das noites.",
    description:
      "A melatonina é o hormônio que regula o ciclo do sono. Auxilia a adormecer com mais facilidade, melhora a qualidade do sono e ajuda a regular o relógio biológico, especialmente em rotinas irregulares.",
    benefits: ["Adormece mais rápido", "Sono mais profundo", "Regula o ciclo"],
    badges: ["Manipulado", "Sublingual"],
    bestseller: true,
    special: true,
  },
  {
    id: "p15",
    slug: "triptofano-magnesio-noite",
    name: "Triptofano + Magnésio Noite",
    category: "sono",
    price: 64.9,
    rating: 4.6,
    reviews: 96,
    shortDescription: "Relaxamento e bem-estar para noites tranquilas.",
    description:
      "Combinação de L-triptofano, magnésio e vitamina B6 que favorece a produção de serotonina e melatonina, promovendo relaxamento, bem-estar e um sono reparador.",
    benefits: ["Relaxa o corpo", "Reduz o estresse", "Sono reparador"],
    badges: ["Manipulado", "Vegano"],
  },
  {
    id: "p16",
    slug: "serum-vitamina-c-manipulado",
    name: "Sérum Facial Vitamina C 10%",
    category: "dermato",
    price: 109.9,
    oldPrice: 139.9,
    rating: 4.9,
    reviews: 205,
    shortDescription: "Ilumina, uniformiza e protege a pele do rosto.",
    description:
      "Sérum facial manipulado com vitamina C estabilizada a 10%, ácido ferúlico e vitamina E. Ilumina o tom da pele, uniformiza manchas e protege contra os radicais livres. Textura leve de rápida absorção.",
    benefits: ["Ilumina a pele", "Reduz manchas", "Antioxidante potente"],
    badges: ["Manipulado", "Uso tópico"],
    special: true,
  },
  {
    id: "p17",
    slug: "creme-acido-hialuronico",
    name: "Creme Facial Ácido Hialurônico",
    category: "dermato",
    price: 89.9,
    rating: 4.7,
    reviews: 158,
    shortDescription: "Hidratação profunda e efeito preenchedor.",
    description:
      "Creme facial manipulado com ácido hialurônico de diferentes pesos moleculares para hidratação profunda e efeito preenchedor, suavizando linhas finas e devolvendo viço à pele.",
    benefits: ["Hidratação profunda", "Efeito preenchedor", "Suaviza linhas finas"],
    badges: ["Manipulado", "Uso tópico"],
  },
  {
    id: "p18",
    slug: "multivitaminico-a-z",
    name: "Multivitamínico A-Z Personalizado",
    category: "saude",
    price: 79.9,
    rating: 4.7,
    reviews: 264,
    shortDescription: "Todas as vitaminas e minerais essenciais em uma cápsula.",
    description:
      "Fórmula completa com vitaminas de A a Z e minerais essenciais, ajustável às suas necessidades. Suporte diário para energia, imunidade e bem-estar geral, manipulado conforme seu perfil.",
    benefits: ["Suporte diário completo", "Mais energia", "Personalizável"],
    badges: ["Manipulado", "Personalizável"],
    bestseller: true,
  },
];

export const banners: Banner[] = [
  {
    id: "b1",
    eyebrow: "Farmácia de Manipulação",
    title: "Fórmulas sob medida, feitas para o seu corpo",
    subtitle:
      "Manipulados com precisão farmacêutica, ingredientes de alta pureza e o cuidado que você merece.",
    ctaLabel: "Explorar produtos",
    ctaHref: "/produtos",
    align: "left",
    gradient: ["#12261C", "#1B4332"],
    icon: "FlaskConical",
  },
  {
    id: "b2",
    eyebrow: "Clube Tua",
    title: "Até 20% OFF e frete grátis todo mês",
    subtitle:
      "Entre para o Clube de Vantagens Tua Pharma e receba benefícios exclusivos, cashback e brindes.",
    ctaLabel: "Conhecer o Clube",
    ctaHref: "/clube",
    align: "left",
    gradient: ["#1B4332", "#0C1E16"],
    icon: "Crown",
  },
  {
    id: "b3",
    eyebrow: "Praticidade",
    title: "Envie sua receita e manipule com segurança",
    subtitle:
      "Nossos farmacêuticos analisam sua receita e preparam sua fórmula com todo o rigor técnico.",
    ctaLabel: "Enviar receita",
    ctaHref: "/receita",
    align: "left",
    gradient: ["#163B2C", "#245A42"],
    icon: "FileText",
  },
];

// Regras do Clube de Vantagens Tua (programa de pontos gratuito)
export const POINTS_PER_REAL = 1; // 1 ponto a cada R$ 1 gasto
export const MIN_REDEEM = 200; // pontos mínimos para trocar por prêmios

export const clubRewards: Reward[] = [
  {
    id: "r1",
    name: "Cupom R$ 15 OFF",
    description: "Desconto de R$ 15 na sua próxima compra.",
    points: 200,
    icon: "Ticket",
  },
  {
    id: "r2",
    name: "Frete grátis",
    description: "Frete grátis garantido no próximo pedido.",
    points: 300,
    icon: "Truck",
  },
  {
    id: "r3",
    name: "Brinde surpresa Tua",
    description: "Um mimo exclusivo da Tua Pharma para você.",
    points: 450,
    icon: "Gift",
  },
  {
    id: "r4",
    name: "Cupom R$ 40 OFF",
    description: "Desconto de R$ 40 em compras acima de R$ 150.",
    points: 600,
    icon: "Ticket",
  },
  {
    id: "r5",
    name: "Vitamina C Lipossomal grátis",
    description: "Resgate um frasco por nossa conta.",
    points: 1000,
    icon: "Pill",
  },
  {
    id: "r6",
    name: "Kit Skincare Manipulado",
    description: "Sérum + creme facial manipulados exclusivos.",
    points: 1500,
    icon: "Sparkles",
  },
  {
    id: "r7",
    name: "R$ 100 em créditos",
    description: "Cem reais de crédito para usar como quiser.",
    points: 2000,
    icon: "Coins",
  },
];

export const productBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);

export const categoryBySlug = (slug: string): Category | undefined =>
  categories.find((c) => c.slug === slug);

export const productsByCategory = (slug: string): Product[] =>
  products.filter((p) => p.category === slug);

export const specialOffers = (): Product[] => products.filter((p) => p.special);

export const bestsellers = (): Product[] => products.filter((p) => p.bestseller);
